"""Make Kaliningrad properly findable in the dropdown.

The first pass picked a marshalling yard ('Западный-Новый') as the
anchor — fine for the graph but invisible to a user looking for
'Kaliningrad'. Add the actual passenger terminal as a curated node
('kaliningrad_main' id, name 'Kaliningrad') and re-anchor the Moscow
+ StP sleepers to it. Also add Chernyakhovsk on the BTK transit line
and Baltiysk as the western terminus.
"""
import re, sys, io, math
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

target = r'c:\Users\darkl\OneDrive\Desktop\chronotrain\data_ru.js'
s = open(target, encoding='utf-8').read()

ADDS = [
    # curated id, English, Russian, lat, lng
    ("kaliningrad_main",   "Kaliningrad",   "Калининград-Пассажирский", 54.6934, 20.4986),
    ("chernyakhovsk",      "Chernyakhovsk", "Черняховск",               54.6285, 21.8188),
    ("baltiysk",           "Baltiysk",      "Балтийск",                 54.6443, 19.8967),
]

EDGES = [
    # Real RZD intra-oblast times
    ("kaliningrad_main", "chernyakhovsk", 1.5),  # ~120 km eastbound on the Berlin–St P main line
    ("kaliningrad_main", "baltiysk",      0.75), # ~50 km Baltic line
    # Inter-city sleepers (via BY+LT transit)
    ("moscow",        "kaliningrad_main", 22.0), # Strizh #29/30
    ("stpetersburg",  "kaliningrad_main", 26.0), # daily sleeper
]

def quote(x): return '"' + (x or "").replace('\\','\\\\').replace('"','\\"') + '"'

# Drop the earlier autogenerated Moscow ↔ osm_ru_724318331 and stpetersburg ↔ osm_ru_724318331
# anchors so we don't double-count.
s = re.sub(r'^\s*\{ from: "moscow", to: "osm_ru_724318331".*\n', '', s, flags=re.MULTILINE)
s = re.sub(r'^\s*\{ from: "stpetersburg", to: "osm_ru_724318331".*\n', '', s, flags=re.MULTILINE)
# Also re-point all "to: osm_ru_724318331" edges that were the marshalling yard
# to the new kaliningrad_main instead — keeps the existing oblast spurs working.
s = s.replace('to: "osm_ru_724318331"', 'to: "kaliningrad_main"')
s = s.replace('from: "osm_ru_724318331"', 'from: "kaliningrad_main"')

st_block = ["  // Kaliningrad oblast — curated anchors with user-recognisable names"]
for sid, en, ru, lat, lng in ADDS:
    st_block.append(f'  {{ id: {quote(sid)}, name: {quote(en)}, native: {quote(ru)}, country: "RU", lat: {lat}, lng: {lng} }},')

rt_block = ["  // Kaliningrad oblast — RZD sleeper anchors (via BY/LT transit) + intra-oblast"]
for f, t, h in EDGES:
    line = "Kaliningrad sleeper (BY/LT transit)" if "kaliningrad_main" in (f, t) and h >= 10 else "RZD Kaliningrad oblast"
    rt_block.append(f'  {{ from: {quote(f)}, to: {quote(t)}, h: {h}, type: "conv", line: {quote(line)}, op: "RZD" }},')

m1 = re.search(r'(window\.EXTRA_STATIONS_RU\s*=\s*\[[\s\S]*?)(\n\];)', s)
s = s[:m1.end(1)] + "\n" + "\n".join(st_block) + m1.group(2) + s[m1.end():]
m2 = re.search(r'(window\.EXTRA_ROUTES_RU\s*=\s*\[[\s\S]*?)(\n\];)', s)
s = s[:m2.end(1)] + "\n" + "\n".join(rt_block) + m2.group(2) + s[m2.end():]
open(target, 'w', encoding='utf-8').write(s)
print("wrote data_ru.js with kaliningrad_main + chernyakhovsk + baltiysk")
